=== synchronoss/cpo-api/cpo-core/src/main/resources/xsd/CpoMeta.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://www.synchronoss.org/cpo/CpoMeta.xsd"
    targetNamespace="http://www.synchronoss.org/cpo/CpoMeta.xsd"
    elementFormDefault="qualified">
    
    <xs:element name="cpoMetaData" type="ctCpoMetaData"/>
    
    <xs:complexType name="ctCpoMetaData">
        <xs:sequence>
            <xs:element name="cpoClass" type="ctClass" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="metaDescriptor" type="xs:string" use="required"/>

        <!-- used by cpo util to store the package name -->
        <xs:attribute name="defaultPackageName" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:complexType name="ctClass">
        <xs:sequence>
            <xs:element ref="cpoAttribute" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="cpoFunctionGroup" type="ctFunctionGroup" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="ctFunctionGroup">
        <xs:sequence>
            <xs:element name="cpoFunction" type="ctFunction" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="optional"/>
        <xs:attribute name="type" type="stFunctionGroupType" use="required"/>
    </xs:complexType>

    <xs:simpleType name="stFunctionGroupType">
      <xs:restriction base="xs:string">
        <xs:enumeration value="CREATE"/>
        <xs:enumeration value="DELETE"/>
        <xs:enumeration value="EXECUTE"/>
        <xs:enumeration value="EXIST"/>
        <xs:enumeration value="LIST"/>
        <xs:enumeration value="RETRIEVE"/>
        <xs:enumeration value="UPDATE"/>
      </xs:restriction>
    </xs:simpleType>

    <xs:element name="cpoAttribute" type="ctAttribute"/>

    <xs:complexType name="ctAttribute">
        <xs:sequence>
            <xs:element name="javaName" type="xs:string"/>
            <xs:element name="javaType" type="xs:string"/>
            <xs:element name="dataName" type="xs:string"/>
            <xs:element name="dataType" type="xs:string"/>
            <xs:element name="transformClass" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ctFunction">
        <xs:sequence>
            <xs:element name="expression" type="xs:string"/>
            <xs:element ref="cpoArgument" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:element name="cpoArgument" type="ctArgument"/>

    <xs:complexType name="ctArgument">
        <xs:sequence>
            <xs:element name="attributeName" type="xs:string"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <!--  JDBC Definitions  -->

    <xs:complexType name="ctJdbcAttribute" >
        <xs:complexContent>
            <xs:extension base="ctAttribute">
                <xs:sequence>
                    <xs:element name="dbTable" type="xs:string" minOccurs="0"/>
                    <xs:element name="dbColumn" type="xs:string" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="jdbcAttribute" type="ctJdbcAttribute" substitutionGroup="cpoAttribute"/>

    <xs:complexType name="ctJdbcArgument">
        <xs:complexContent>
            <xs:extension base="ctArgument">
                <xs:sequence minOccurs="0">
                    <xs:element name="scope" default="IN" type="stArgumentScope">
                    </xs:element>
                    <xs:element name="typeInfo" type="xs:string" minOccurs="0" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="jdbcArgument" type="ctJdbcArgument" substitutionGroup="cpoArgument"/>

    <xs:simpleType name="stArgumentScope">
        <xs:restriction base="xs:string">
            <xs:enumeration value="IN"/>
            <xs:enumeration value="OUT"/>
            <xs:enumeration value="BOTH"/>
        </xs:restriction>
    </xs:simpleType>

    <!--  Cassandra Definitions  -->

    <xs:element name="cassandraAttribute" type="ctCassandraAttribute" substitutionGroup="cpoAttribute"/>

    <xs:complexType name="ctCassandraAttribute" >
        <xs:complexContent>
            <xs:extension base="ctAttribute">
                <xs:sequence>
                    <xs:element name="keyType" type="xs:string" minOccurs="0"/>
                    <xs:element name="valueType" type="xs:string" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="cassandraArgument" type="ctCassandraArgument" substitutionGroup="cpoArgument"/>

    <xs:complexType name="ctCassandraArgument">
        <xs:complexContent>
            <xs:extension base="ctArgument">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

</xs:schema>

=== synchronoss/cpo-api/cpo-cassandra/src/test/resources/cassandraMetaData.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  [[
  cassandra
  ==
  Copyright (C) 2003 - 2026 Exaxis LLC, Synchronoss Technologies Inc
  ==
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License as
  published by the Free Software Foundation, either version 3 of the
  License, or (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Lesser Public License for more details.
  
  You should have received a copy of the GNU General Lesser Public
  License along with this program.  If not, see
  <http://www.gnu.org/licenses/lgpl-3.0.html>.
  ]]
  -->

<cpoMetaData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.synchronoss.org/cpo/CpoMeta.xsd ../../../../cpo-core/src/main/resources/xsd/CpoMeta.xsd"
             xmlns="http://www.synchronoss.org/cpo/CpoMeta.xsd" metaDescriptor="org.synchronoss.cpo.cassandra.meta.CassandraCpoMetaDescriptor"
 defaultPackageName="">
  <cpoClass name="org.synchronoss.cpo.cassandra.ValueObject">
    <cpoAttribute xsi:type="ctCassandraAttribute">
      <javaName>id</javaName>
      <javaType>int</javaType>
      <dataName>id</dataName>
      <dataType>INT</dataType>
    </cpoAttribute>
    <cpoAttribute xsi:type="ctCassandraAttribute">
      <javaName>attrAscii</javaName>
      <javaType>java.lang.String</javaType>
      <dataName>attr_ascii</dataName>
      <dataType>ASCII</dataType>
    </cpoAttribute>
    <cpoAttribute xsi:type="ctCassandraAttribute">
      <javaName>attrBigInt</javaName>
      <javaType>long</javaType>
      <dataName>attr_bigint</dataName>
      <dataType>BIGINT</dataType>
    </cpoAttribute>
    <cpoAttribute xsi:type="ctCassandraAttribute">
      <javaName>attrBlob</javaName>
      <javaType>java.nio.ByteBuffer</javaType>
      <dataName>attr_blob</dataName>
      <dataType>BLOB</dataType>
    </cpoAttribute>
    <cpoAttribute xsi:type="ctCassandraAttribute">
      <javaName>attrBlob2</javaName>
      <javaType>java.nio.ByteBuffer</javaType>
      <dataName>attr_blob2</dataName>
      <dataType>BLOB</dataType>
    </cpoAttribute>
    <cpoAttribute xsi:type="ctCassandraAttribute">
      <javaName>attrBool</javaName>
      <javaType>boolean</javaType>
      <dataName>attr_bool</dataName>
      <dataType>BOOLEAN</dataType>
    </cpoAttribute>
    <cpoAttribute xsi:type="ctCassandraAttribute">
      <javaName>attrCounter</javaName>
      <javaType>long</javaType>
      <dataName>attr_counter</dataName>
      <dataType>COUNTER</dataType>
    </cpoAttribute>
    <cpoAttribute xsi:type="ctCassandraAttribute">
      <javaName>attrDecimal</javaName>
      <javaType>java.math.BigDecimal</javaType>
      <dataName>attr_decimal</dataName>
      <dataType>DECIMAL</dataType>
    </cpoAttribute>
    <cpoAttribute xsi:type="ctCassandraAttribute">
      <javaName>attrDouble</javaName>
      <javaType>double</javaType>
      <dataName>attr_double</dataName>
      <dataType>DOUBLE</dataType>
    </cpoAttribute>
    <cpoAttribute xsi:type="ctCassandraAttribute">
      <javaName>attrFloat</javaName>
      <javaType>float</javaType>
      <dataName>attr_float</dataName>
      <dataType>FLOAT</dataType>
    </cpoAttribute>
    <cpoAttribute xsi:type="ctCassandraAttribute">
      <javaName>attrInet</javaName>
      <javaType>java.net.InetAddress</javaType>
      <dataName>attr_inet</dataName>
      <dataType>INET</dataType>
    </cpoAttribute>
    <cpoAttribute xsi:type="ctCassandraAttribute">
      <javaName>attrInt</javaName>
      <javaType>int</javaType>
      <dataName>attr_int</dataName>
      <dataType>INT</dataType>
      <transformClass>org.synchronoss.cpo.cassandra.transform.TransformNoOp</transformClass>
    </cpoAttribute>
    <cpoAttribute xsi:type="ctCassandraAttribute">
      <javaName>attrList</javaName>
      <javaType>java.util.List</javaType>
      <dataName>attr_list</dataName>
      <dataType>LIST</dataType>
      <valueType>java.lang.String</valueType>
    </cpoAttribute>
    <cpoAttribute xsi:type="ctCassandraAttribute">
      <javaName>attrMap</javaName>
      <javaType>java.util.Map</javaType>
      <dataName>attr_map</dataName>
      <dataType>MAP</dataType>
      <keyType>java.lang.String</keyType>
      <valueType>java.lang.String</valueType>
    </cpoAttribute>
    <cpoAttribute xsi:type="ctCassandraAttribute">
      <javaName>attrSet</javaName>
      <javaType>java.util.Set</javaType>
      <dataName>attr_set</dataName>
      <dataType>SET</dataType>
      <valueType>java.lang.String</valueType>
    </cpoAttribute>
    <cpoAttribute xsi:type="ctCassandraAttribute">
      <javaName>attrText</javaName>
      <javaType>java.lang.String</javaType>
      <dataName>attr_text</dataName>
      <dataType>TEXT</dataType>
    </cpoAttribute>
    <cpoAttribute xsi:type="ctCassandraAttribute">
      <javaName>attrTimeUUID</javaName>
      <javaType>java.util.UUID</javaType>
      <dataName>attr_timeuuid</dataName>
      <dataType>TIMEUUID</dataType>
    </cpoAttribute>
    <cpoAttribute xsi:type="ctCassandraAttribute">
      <javaName>attrTimestamp</javaName>
      <javaType>java.time.Instant</javaType>
      <dataName>attr_timestamp</dataName>
      <dataType>TIMESTAMP</dataType>
    </cpoAttribute>
    <cpoAttribute xsi:type="ctCassandraAttribute">
      <javaName>attrUUID</javaName>
      <javaType>java.util.UUID</javaType>
      <dataName>attr_uuid</dataName>
      <dataType>UUID</dataType>
    </cpoAttribute>
    <cpoAttribute xsi:type="ctCassandraAttribute">
      <javaName>attrVarChar</javaName>
      <javaType>java.lang.String</javaType>
      <dataName>attr_varchar</dataName>
      <dataType>VARCHAR</dataType>
    </cpoAttribute>
    <cpoAttribute xsi:type="ctCassandraAttribute">
      <javaName>attrVarInt</javaName>
      <javaType>java.math.BigInteger</javaType>
      <dataName>attr_varint</dataName>
      <dataType>VARINT</dataType>
    </cpoAttribute>
    <cpoFunctionGroup type="CREATE">
      <cpoFunction name="ValueObject - Create">
        <expression>insert into value_object(id, attr_ascii, attr_bigint, attr_blob, attr_bool, attr_decimal, attr_double, attr_float, attr_inet, attr_int, attr_text, attr_timestamp, attr_timeuuid, attr_uuid, attr_varchar, attr_varint, attr_list, attr_set, attr_map) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)</expression>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>id</attributeName>
        </cpoArgument>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>attrAscii</attributeName>
        </cpoArgument>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>attrBigInt</attributeName>
        </cpoArgument>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>attrBlob</attributeName>
        </cpoArgument>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>attrBool</attributeName>
        </cpoArgument>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>attrDecimal</attributeName>
        </cpoArgument>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>attrDouble</attributeName>
        </cpoArgument>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>attrFloat</attributeName>
        </cpoArgument>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>attrInet</attributeName>
        </cpoArgument>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>attrInt</attributeName>
        </cpoArgument>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>attrText</attributeName>
        </cpoArgument>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>attrTimestamp</attributeName>
        </cpoArgument>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>attrTimeUUID</attributeName>
        </cpoArgument>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>attrUUID</attributeName>
        </cpoArgument>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>attrVarChar</attributeName>
        </cpoArgument>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>attrVarInt</attributeName>
        </cpoArgument>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>attrList</attributeName>
        </cpoArgument>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>attrSet</attributeName>
        </cpoArgument>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>attrMap</attributeName>
        </cpoArgument>
      </cpoFunction>
    </cpoFunctionGroup>
    <cpoFunctionGroup name="TestOrderByInsert" type="CREATE">
      <cpoFunction name="TestOrderByInsert">
        <expression>insert into value_object (id,attr_varchar,attr_int) values (?,?,?)</expression>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>id</attributeName>
        </cpoArgument>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>attrVarChar</attributeName>
        </cpoArgument>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>attrInt</attributeName>
        </cpoArgument>
      </cpoFunction>
    </cpoFunctionGroup>
    <cpoFunctionGroup type="DELETE">
      <cpoFunction name="ValueObject - Delete">
        <expression>delete from value_object where id = ?</expression>
        <cpoArgument xsi:type="ctCassandraArgument">
          <attributeName>id</attributeName>
        </cpoArgument>
      </cpoFunction>
    </cpoFunctionGroup>
